# Generated by Django 3.2.6 on 2021-08-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_storagea_storageb_storagec_storaged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageA',
            new_name='StorageSixA',
        ),
        migrations.RenameModel(
            old_name='StorageB',
            new_name='StorageSixB',
        ),
        migrations.RenameModel(
            old_name='StorageD',
            new_name='StorageSixC',
        ),
        migrations.RenameModel(
            old_name='StorageC',
            new_name='StorageSixE',
        ),
    ]
