# Generated by Django 3.2.6 on 2021-08-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210814_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagesixa',
            options={'verbose_name_plural': 'StorageSixA'},
        ),
        migrations.AlterModelOptions(
            name='storagesixb',
            options={'verbose_name_plural': 'StorageSixB'},
        ),
        migrations.AlterModelOptions(
            name='storagesixc',
            options={'verbose_name_plural': 'StorageSixC'},
        ),
        migrations.AlterModelOptions(
            name='storagesixe',
            options={'verbose_name_plural': 'StorageSixE'},
        ),
    ]
